In [1]:
import numpy as np
np.__version__

'1.20.1'

In [14]:
p = np.array([1,2,3])
print(type(p))

<class 'numpy.ndarray'>


In [15]:
# Podemos llamar los elementos por posición
print(p[1])

2


In [19]:
a = np.arange(3*2)
print(a)
print(a.shape)
print(a.ndim)

[0 1 2 3 4 5]
(6,)
1


In [29]:
b = a.reshape(3, 2)
print(b.shape)
print(b)

(3, 2)
[[0 1]
 [2 3]
 [4 5]]


In [28]:
print(b[0][0])
print(type(b[0][0]))

0
<class 'numpy.int32'>


In [25]:
# Número de elementos
b.size

6

In [27]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
import platform
print (platform.architecture())

('64bit', 'WindowsPE')


In [35]:
# Ejercicio 1
# Calcula la norma y el determinante de la siguente matriz
m = [[1, 0], [2, -1]]

m = np.array(m)
n = np.linalg.norm(m)
d = np.linalg.det(m)
print(f'La norma es: {n}')
print(f'El determinante es: {d}')

La norma es: 2.449489742783178
El determinante es: -1.0


In [70]:
# Ejercicio 2

arr = np.random.randint(0, 9, 100)
arr = np.array(arr)
# print(arr.size)
print(f'El array aleatorio es: {arr}')
media = arr.mean()
print(f'La media es {media}')
sd = arr.std()
print(f'La desviación típica es {sd}')
minimo = arr.min()
print(f'El valor mínimo es {minimo}')
maximo = arr.max()
print(f'El valor máximo es {maximo}')
suma = arr.sum()
print(f'La suma de todos los elememntos es {suma}')
unicos = np.unique(arr)
print(f'Y aquí tenemos los elementos unicos: {unicos}')


El array aleatorio es: [8 7 2 4 5 4 2 7 4 4 1 7 4 1 6 2 2 8 4 6 4 7 8 6 3 3 0 3 3 3 1 2 4 6 7 0 7
 3 0 8 1 5 6 3 3 6 2 2 5 1 7 6 0 8 5 2 4 8 1 2 6 4 7 4 3 1 3 7 8 5 0 3 0 0
 1 1 5 0 8 4 7 2 0 4 1 1 7 1 8 6 2 3 5 6 0 4 4 2 7 3]
La media es 3.86
La desviación típica es 2.5020791354391654
El valor mínimo es 0
El valor máximo es 8
La suma de todos los elememntos es 386
Y aquí tenemos los elementos unicos: [0 1 2 3 4 5 6 7 8]


In [91]:
# Ejercicio 3
from random import randint
mat1 = np.array([[randint(0, 9) for x in range(5)] for x in range(5)])
mat1 = mat1.reshape(5, 5)
mat2 = np.array([[randint(0, 9) for x in range(5)] for x in range(5)])
mat2 = mat2.reshape(5, 5)
print(mat1)
print()
print(mat2)
print()
p1 = mat1 * mat2
print(p1)
print()
p2 = mat1.dot(mat2)
print(p2)

mat3 = np.random.rand(4, 5)
print(mat3)

[[2 4 2 5 3]
 [1 3 6 7 0]
 [3 3 6 2 0]
 [1 6 1 2 7]
 [0 9 3 8 7]]

[[5 4 5 3 4]
 [4 6 2 9 9]
 [8 5 1 2 2]
 [4 8 6 0 2]
 [0 7 3 0 9]]

[[10 16 10 15 12]
 [ 4 18 12 63  0]
 [24 15  6  4  0]
 [ 4 48  6  0 14]
 [ 0 63  9  0 63]]

[[ 62 103  59  46  85]
 [ 93 108  59  42  57]
 [ 83  76  39  48  55]
 [ 45 110  51  59 127]
 [ 92 182  90  87 166]]
[[0.91253229 0.97745842 0.48041532 0.82949378 0.22842917]
 [0.64255992 0.27512183 0.29702511 0.45902548 0.34474678]
 [0.81186999 0.55176905 0.32624129 0.86226027 0.67488872]
 [0.75373873 0.41000011 0.01069123 0.19391755 0.73279023]]


In [117]:
import pandas as pd
df = pd.DataFrame()
df = pd.read_csv('tempAndHum.csv')
df.head()
df.describe()

NO.
count  18609.000000
mean    9305.000000
std     5372.099915
min        1.000000
25%     4653.000000
50%     9305.000000
75%    13957.000000
max    18609.000000

In [111]:
import pandas as pd
data = pd.read_csv('marvel-wikia-data.csv')
data.describe()

page_id   APPEARANCES          Year
count   16376.000000  15280.000000  15561.000000
mean   300232.082377     17.033377   1984.951803
std    253460.403399     96.372959     19.663571
min      1025.000000      1.000000   1939.000000
25%     28309.500000      1.000000   1974.000000
50%    282578.000000      3.000000   1990.000000
75%    509077.000000      8.000000   2000.000000
max    755278.000000   4043.000000   2013.000000

In [4]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/marcusRB/IDbootcamps_DataScience_student_PT_10201/master/dataset/earthquakes.csv')

In [6]:
df[['mag', 'alert', 'title']]

mag alert                                     title
0     1.35   NaN             M 1.4 - 9km NE of Aguanga, CA
1     1.29   NaN             M 1.3 - 9km NE of Aguanga, CA
2     3.42   NaN             M 3.4 - 8km NE of Aguanga, CA
3     0.44   NaN             M 0.4 - 9km NE of Aguanga, CA
4     2.16   NaN             M 2.2 - 10km NW of Avenal, CA
...    ...   ...                                       ...
9327  0.62   NaN      M 0.6 - 9km ENE of Mammoth Lakes, CA
9328  1.00   NaN               M 1.0 - 3km W of Julian, CA
9329  2.40   NaN  M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330  1.10   NaN             M 1.1 - 9km NE of Aguanga, CA
9331  0.66   NaN             M 0.7 - 9km NE of Aguanga, CA

[9332 rows x 3 columns]

In [17]:
condiciones = ['alert', 'mag', 'magType', 'title', 'type', 'tsunami', 'time']
tsunami = df[df.tsunami == 1][condiciones]
redAlert = df[df.alert == 'red'][condiciones]
result = pd.concat([tsunami, redAlert])

result



alert  mag magType                                              title  \
36      NaN  5.0     mww  M 5.0 - 165km NNW of Flying Fish Cove, Christm...   
118   green  6.7     mww            M 6.7 - 262km NW of Ozernovskiy, Russia   
501   green  5.6     mww        M 5.6 - 128km SE of Kimbe, Papua New Guinea   
799   green  6.5     mww         M 6.5 - 148km S of Severo-Kuril'sk, Russia   
816   green  6.2     mww        M 6.2 - 94km SW of Kokopo, Papua New Guinea   
...     ...  ...     ...                                                ...   
8624    NaN  5.1      mb       M 5.1 - 278km SE of Pondaguitan, Philippines   
9133  green  5.1      ml               M 5.1 - 64km SSW of Kaktovik, Alaska   
9175    NaN  5.2      mb                M 5.2 - 126km N of Dili, East Timor   
9304    NaN  5.1      mb   M 5.1 - 34km NW of Finschhafen, Papua New Guinea   
5263    red  7.5     mww                  M 7.5 - 78km N of Palu, Indonesia   

            type  tsunami           time  
36    earthquake        1  1539459504090  
118   earthquake        1  1539429023560  
501   earthquake        1  1539312723620  
799   earthquake        1  1539213362130  
816   earthquake        1  1539208835130  
...          ...      ...            ...  
8624  earthquake        1  1537411002190  
9133  earthquake        1  1537274456960  
9175  earthquake        1  1537262729590  
9304  earthquake        1  1537236235470  
5263  earthquake        1  1538128963480  

[62 rows x 7 columns]

In [18]:
cols = ['time','title','place','magType','mag','alert','type','tsunami']
df = pd.read_csv('https://raw.githubusercontent.com/marcusRB/IDbootcamps_DataScience_student_PT_10201/master/dataset/earthquakes.csv', usecols=cols)
df.sample(10, random_state=17)

alert   mag magType                             place           time  \
6944   NaN  0.14      ml            10km NE of Aguanga, CA  1537802395980   
1874   NaN  0.56      md         8km NW of The Geysers, CA  1538881523580   
7897   NaN  4.90      mb  105km WSW of Saumlaki, Indonesia  1537597991110   
4088   NaN -0.18      ml       22km NNE of Dillon, Montana  1538358406620   
7373   NaN  1.90      ml      33km S of Dillingham, Alaska  1537716376264   
5397   NaN  1.44      ml         20km NNW of Tehachapi, CA  1538097736850   
7847   NaN  0.41      md       13km ESE of Millville, Utah  1537610054650   
4357   NaN  0.54      ml             9km NE of Aguanga, CA  1538305264440   
1176   NaN  1.40      ml  118km SSE of Prudhoe Bay, Alaska  1539095359794   
8165   NaN  2.25      ml      21km NW of Montpelier, Idaho  1537524389750   

                                         title  tsunami        type  
6944            M 0.1 - 10km NE of Aguanga, CA        0  earthquake  
1874         M 0.6 - 8km NW of The Geysers, CA        0  earthquake  
7897  M 4.9 - 105km WSW of Saumlaki, Indonesia        0  earthquake  
4088      M -0.2 - 22km NNE of Dillon, Montana        0  earthquake  
7373      M 1.9 - 33km S of Dillingham, Alaska        0  earthquake  
5397         M 1.4 - 20km NNW of Tehachapi, CA        0  earthquake  
7847       M 0.4 - 13km ESE of Millville, Utah        0  earthquake  
4357             M 0.5 - 9km NE of Aguanga, CA        0  earthquake  
1176  M 1.4 - 118km SSE of Prudhoe Bay, Alaska        0  earthquake  
8165      M 2.3 - 21km NW of Montpelier, Idaho        0  earthquake

In [28]:
df['nuevo'] = df.mag < 0
df.sample(20)

alert   mag magType                                place           time  \
6961   NaN  4.70      mb            46km ENE of Hirara, Japan  1537799121060   
8933   NaN  1.30      ml            61km SSW of Kobuk, Alaska  1537324298744   
1779   NaN  0.33      ml           31km W of Unalaska, Alaska  1538909027830   
9164   NaN  1.27      ml     78km NNE of Chignik Lake, Alaska  1537264857620   
7298   NaN  1.80      ml             34km W of Willow, Alaska  1537728707560   
3687   NaN  2.00      ml  122km NNW of Arctic Village, Alaska  1538440584052   
1987   NaN  2.70      ml    8km NE of Incline Village, Nevada  1538856668466   
7381   NaN  4.60      mb       9km ENE of Funaishikawa, Japan  1537715134540   
6402   NaN  1.10      ml         77km SSW of Kaktovik, Alaska  1537906943565   
9262   NaN  1.26      md            15km SSE of Parowan, Utah  1537245016420   
4307   NaN  0.10      ml           50km ENE of Beatty, Nevada  1538314523613   
3292   NaN  4.20      mb       275km NNE of Ndoi Island, Fiji  1538528612970   
3627   NaN  0.53      ml                8km NE of Aguanga, CA  1538451456150   
6965   NaN  2.04      md             8km ENE of Pinnacles, CA  1537797505720   
510    NaN  1.80      ml    100km N of Arctic Village, Alaska  1539308570929   
940    NaN  1.91      ml          2km W of Manhattan, Montana  1539174678840   
1391   NaN  1.40      ml           34km NNW of Valdez, Alaska  1539036389022   
3437   NaN  2.50      ml     45km ESE of Chignik Lake, Alaska  1538495645548   
1145   NaN  1.59      ml         5km WNW of Coso Junction, CA  1539106530710   
2178   NaN  1.10      ml          58km W of Anchorage, Alaska  1538803721099   

                                            title  tsunami        type  nuevo  
6961            M 4.7 - 46km ENE of Hirara, Japan        0  earthquake  False  
8933            M 1.3 - 61km SSW of Kobuk, Alaska        0  earthquake  False  
1779           M 0.3 - 31km W of Unalaska, Alaska        0  earthquake  False  
9164     M 1.3 - 78km NNE of Chignik Lake, Alaska        0  earthquake  False  
7298             M 1.8 - 34km W of Willow, Alaska        0  earthquake  False  
3687  M 2.0 - 122km NNW of Arctic Village, Alaska        0  earthquake  False  
1987    M 2.7 - 8km NE of Incline Village, Nevada        0  earthquake  False  
7381       M 4.6 - 9km ENE of Funaishikawa, Japan        0  earthquake  False  
6402         M 1.1 - 77km SSW of Kaktovik, Alaska        0  earthquake  False  
9262            M 1.3 - 15km SSE of Parowan, Utah        0  earthquake  False  
4307           M 0.1 - 50km ENE of Beatty, Nevada        0  earthquake  False  
3292       M 4.2 - 275km NNE of Ndoi Island, Fiji        0  earthquake  False  
3627                M 0.5 - 8km NE of Aguanga, CA        0  earthquake  False  
6965             M 2.0 - 8km ENE of Pinnacles, CA        0  earthquake  False  
510     M 1.8 - 100km N of Arctic Village, Alaska        0  earthquake  False  
940           M 1.9 - 2km W of Manhattan, Montana        0  earthquake  False  
1391           M 1.4 - 34km NNW of Valdez, Alaska        0  earthquake  False  
3437     M 2.5 - 45km ESE of Chignik Lake, Alaska        0  earthquake  False  
1145         M 1.6 - 5km WNW of Coso Junction, CA        0  earthquake  False  
2178          M 1.1 - 58km W of Anchorage, Alaska        0  earthquake  False

In [29]:
# Operamos con expresiones regulares
df['place'].str.extract(r', (.*$)')[0].sort_values().unique()

array(['Afghanistan', 'Alaska', 'Argentina', 'Arizona', 'Arkansas',
       'Australia', 'Azerbaijan', 'B.C., MX', 'Barbuda', 'Bolivia',
       'Bonaire, Saint Eustatius and Saba ', 'British Virgin Islands',
       'Burma', 'CA', 'California', 'Canada', 'Chile', 'China',
       'Christmas Island', 'Colombia', 'Colorado', 'Costa Rica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'Ecuador region',
       'El Salvador', 'Fiji', 'Greece', 'Greenland', 'Guam', 'Guatemala',
       'Haiti', 'Hawaii', 'Honduras', 'Idaho', 'Illinois', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Italy', 'Jamaica', 'Japan', 'Kansas',
       'Kentucky', 'Kyrgyzstan', 'Martinique', 'Mauritius', 'Mayotte',
       'Mexico', 'Missouri', 'Montana', 'NV', 'Nevada', 'New Caledonia',
       'New Hampshire', 'New Mexico', 'New Zealand', 'Nicaragua',
       'North Carolina', 'Northern Mariana Islands', 'Oklahoma', 'Oregon',
       'Pakistan', 'Papua New Guinea', 'Peru', 'Philippines',
       'Puerto Rico', 'Roman

In [30]:
# Operamos con transformación de unos valores
df['parsed_place'] = df['place'].str.replace(
    r'.* of ', '', regex=True # elimina cualquier término que tenga of
).str.replace(
    'the ', '' # eliminamos "the "
).str.replace(
    r'CA$', 'California', regex=True # sustituye CA por California
).str.replace(
    r'NV$', 'Nevada', regex=True # sustituye NV por Nevada
).str.replace(
    r'MX$', 'Mexico', regex=True # sustituye MX por Mexico
).str.replace(
    r' region$', '', regex=True # elimina el término region
).str.replace(
    'northen ', '' # eliminamos 'northen ' 
).str.replace(
    'Fiji Islands', 'Fiji' # renombramos Fiji Island por Fiji
).str.replace(
    r'^.*, ', '', regex=True # elimina cualquier elemento raro desde el principio
).str.replace(
    r'Fiji Islan[a-zA-Z0-9]{1,}', 'Fiji', regex=True
).str.strip() # elimina espacios
df

alert   mag magType                             place           time  \
0      NaN  1.35      ml             9km NE of Aguanga, CA  1539475168010   
1      NaN  1.29      ml             9km NE of Aguanga, CA  1539475129610   
2      NaN  3.42      ml             8km NE of Aguanga, CA  1539475062610   
3      NaN  0.44      ml             9km NE of Aguanga, CA  1539474978070   
4      NaN  2.16      md             10km NW of Avenal, CA  1539474716050   
...    ...   ...     ...                               ...            ...   
9327   NaN  0.62      md      9km ENE of Mammoth Lakes, CA  1537230228060   
9328   NaN  1.00      ml               3km W of Julian, CA  1537230135130   
9329   NaN  2.40      md  35km NNE of Hatillo, Puerto Rico  1537229908180   
9330   NaN  1.10      ml             9km NE of Aguanga, CA  1537229545350   
9331   NaN  0.66      ml             9km NE of Aguanga, CA  1537228864470   

                                         title  tsunami        type  nuevo  \
0                M 1.4 - 9km NE of Aguanga, CA        0  earthquake  False   
1                M 1.3 - 9km NE of Aguanga, CA        0  earthquake  False   
2                M 3.4 - 8km NE of Aguanga, CA        0  earthquake  False   
3                M 0.4 - 9km NE of Aguanga, CA        0  earthquake  False   
4                M 2.2 - 10km NW of Avenal, CA        0  earthquake  False   
...                                        ...      ...         ...    ...   
9327      M 0.6 - 9km ENE of Mammoth Lakes, CA        0  earthquake  False   
9328               M 1.0 - 3km W of Julian, CA        0  earthquake  False   
9329  M 2.4 - 35km NNE of Hatillo, Puerto Rico        0  earthquake  False   
9330             M 1.1 - 9km NE of Aguanga, CA        0  earthquake  False   
9331             M 0.7 - 9km NE of Aguanga, CA        0  earthquake  False   

     parsed_place  
0      California  
1      California  
2      California  
3      California  
4      California  
...           ...  
9327   California  
9328   California  
9329  Puerto Rico  
9330   California  
9331   California  

[9332 rows x 10 columns]

In [58]:
# Podemos hacer uso de assign() para crear columnas
df = df.assign(
    in_ca=df['parsed_place'].str.endswith('California'),
    in_alaska=df['parsed_place'].str.endswith('Alaska'),
    no = (df['in_ca'] == False) & (df['in_alaska'] == False)
).sample(20, random_state=20)
df[['parsed_place', 'in_ca', 'in_alaska', 'no']]

parsed_place  in_ca  in_alaska     no
4697       Alaska  False       True  False
255        Nevada  False      False   True
9280   California   True      False  False
5620   California   True      False  False
8127        Idaho  False      False   True
4570   California   True      False  False
376        Alaska  False       True  False
984    California   True      False  False
2617   California   True      False  False
426        Alaska  False       True  False
2786       Nevada  False      False   True
1291       Alaska  False       True  False
4745   California   True      False  False
2814   California   True      False  False
7494   California   True      False  False
7500         Fiji  False      False   True
8097   California   True      False  False
8817   California   True      False  False
4161  Puerto Rico  False      False   True
8225       Alaska  False       True  False